Repository sighupio/getting-started, pull requests merged in 2023-04, with the labels that each got.

#38 feat(ovh): update guide to KFD 1.25.1
  README.md
  fury-on-ovhcloud/Furyfile.yml
  fury-on-ovhcloud/README.md
  fury-on-ovhcloud/infrastructure/terraform/modules/kubernetes/k8s_pvnw/variables.tfvars
  fury-on-ovhcloud/infrastructure/terraform/variables.tfvars
  fury-on-ovhcloud/manifests/logging/kustomization.yaml
Labels: enhancement

#35 feat(eks): update guide to Kubernetes 1.25 and KFD 1.25.0
  README.md
  fury-on-eks/Furyfile.yml
  fury-on-eks/README.md
  fury-on-eks/infrastructure/bootstrap.yml
  fury-on-eks/infrastructure/cluster.yml
  fury-on-eks/manifests/logging/kustomization.yaml
  fury-on-eks/manifests/opa/kustomization.yaml
  fury-on-eks/manifests/opa/resources/ingress.yml
  fury-on-eks/terraform/main.tf
Labels: documentation, enhancement

#41 fix: env var in dockerfile
  utils/docker/Dockerfile
Labels: bug
